# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69174c806e010f3c56fc5b7120768f5fdfbc984c6b9ac848d1f38bace8e7e2fca0aecd58e8241be3668794c21d06c9e295b0d97e4bc4269b73f711231367f962

test:
  secret_key_base: 3d06e40384006c6cb6a9901ff154f2f70e5755fd7790fa815ea94d99dd0fc3c84cb21b06fb65a4a3719221e8ab464062e32a68d8b86a502938d7745f24621cbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
